from django.test import TestCase, Client
from django.urls import reverse
from django.contrib.auth.models import User
from django.core import mail
from django.core.files.uploadedfile import SimpleUploadedFile

from .models import JobCategory, Skill, Company, JobPosting, JobSkill, SavedJob, Application, JobReview


class JobModelTests(TestCase):
    def setUp(self):
        self.category = JobCategory.objects.create(name='Software Engineering')
        self.company = Company.objects.create(name='Acme Corp', industry='Tech')
        self.skill = Skill.objects.create(name='Python')
        self.job = JobPosting.objects.create(
            title='Backend Engineer', company=self.company, category=self.category,
            description='Build things.', location='Remote', salary_min=90000, salary_max=120000,
        )

    def test_slug_autogenerated(self):
        self.assertTrue(self.job.slug)
        self.assertIn('backend-engineer', self.job.slug)

    def test_unique_slug_on_duplicate_title(self):
        job2 = JobPosting.objects.create(
            title='Backend Engineer', company=self.company, category=self.category,
            description='Another one.', location='Remote',
        )
        self.assertNotEqual(self.job.slug, job2.slug)

    def test_salary_display(self):
        self.assertIn('90,000', self.job.salary_display)
        self.assertIn('120,000', self.job.salary_display)

    def test_salary_display_no_salary(self):
        job = JobPosting.objects.create(
            title='Mystery Role', company=self.company, category=self.category,
            description='?', location='Remote',
        )
        self.assertEqual(job.salary_display, 'Not disclosed')

    def test_job_skill_weight(self):
        js = JobSkill.objects.create(job=self.job, skill=self.skill, importance='required')
        self.assertEqual(js.weight, 3)
        js.importance = 'nice_to_have'
        self.assertEqual(js.weight, 1)

    def test_company_active_job_count(self):
        self.assertEqual(self.company.active_job_count, 1)
        JobPosting.objects.create(
            title='Inactive Role', company=self.company, category=self.category,
            description='...', location='Remote', is_active=False,
        )
        self.assertEqual(self.company.active_job_count, 1)


class JobViewTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.category = JobCategory.objects.create(name='Data Science & Analytics')
        self.company = Company.objects.create(name='DataCorp')
        self.skill = Skill.objects.create(name='SQL')
        self.job = JobPosting.objects.create(
            title='Data Analyst', company=self.company, category=self.category,
            description='Analyze data.', location='New York, NY', salary_min=70000, salary_max=95000,
        )
        JobSkill.objects.create(job=self.job, skill=self.skill, importance='required')
        self.user = User.objects.create_user(username='tester', password='testpass123')

    def test_home_page_loads(self):
        response = self.client.get(reverse('jobs:home'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Data Analyst')

    def test_job_list_loads(self):
        response = self.client.get(reverse('jobs:job_list'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Data Analyst')

    def test_job_list_keyword_filter(self):
        response = self.client.get(reverse('jobs:job_list'), {'q': 'Data Analyst'})
        self.assertContains(response, 'Data Analyst')
        response = self.client.get(reverse('jobs:job_list'), {'q': 'Nonexistent Role XYZ'})
        self.assertNotContains(response, 'Data Analyst')

    def test_job_list_location_filter(self):
        response = self.client.get(reverse('jobs:job_list'), {'location': 'New York'})
        self.assertContains(response, 'Data Analyst')
        response = self.client.get(reverse('jobs:job_list'), {'location': 'Nowhere'})
        self.assertNotContains(response, 'Data Analyst')

    def test_job_detail_increments_views(self):
        initial_views = self.job.views_count
        response = self.client.get(self.job.get_absolute_url())
        self.assertEqual(response.status_code, 200)
        self.job.refresh_from_db()
        self.assertEqual(self.job.views_count, initial_views + 1)

    def test_job_detail_404_for_bad_slug(self):
        response = self.client.get('/jobs/does-not-exist/')
        self.assertEqual(response.status_code, 404)

    def test_save_job_requires_login(self):
        response = self.client.post(reverse('jobs:toggle_save_job', args=[self.job.slug]))
        self.assertEqual(response.status_code, 302)
        self.assertIn('/accounts/login/', response.url)

    def test_save_and_unsave_job(self):
        self.client.login(username='tester', password='testpass123')
        response = self.client.post(reverse('jobs:toggle_save_job', args=[self.job.slug]))
        self.assertEqual(response.status_code, 302)
        self.assertTrue(SavedJob.objects.filter(user=self.user, job=self.job).exists())

        response = self.client.post(reverse('jobs:toggle_save_job', args=[self.job.slug]))
        self.assertFalse(SavedJob.objects.filter(user=self.user, job=self.job).exists())

    def test_apply_to_job(self):
        self.client.login(username='tester', password='testpass123')
        response = self.client.post(reverse('jobs:apply_to_job', args=[self.job.slug]))
        self.assertEqual(response.status_code, 302)
        self.assertTrue(Application.objects.filter(user=self.user, job=self.job).exists())

    def test_apply_twice_does_not_duplicate(self):
        self.client.login(username='tester', password='testpass123')
        self.client.post(reverse('jobs:apply_to_job', args=[self.job.slug]))
        self.client.post(reverse('jobs:apply_to_job', args=[self.job.slug]))
        self.assertEqual(Application.objects.filter(user=self.user, job=self.job).count(), 1)

    def test_company_detail_page(self):
        response = self.client.get(self.company.get_absolute_url())
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.company.name)

    def test_company_review_requires_login(self):
        response = self.client.get(self.company.get_absolute_url())
        self.assertNotContains(response, 'Post review')

    def test_category_and_skill_detail_pages(self):
        response = self.client.get(self.category.get_absolute_url())
        self.assertEqual(response.status_code, 200)
        response = self.client.get(self.skill.get_absolute_url())
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Data Analyst')


class JobAPITests(TestCase):
    def setUp(self):
        self.client = Client()
        self.category = JobCategory.objects.create(name='Design (UX/UI)')
        self.company = Company.objects.create(name='DesignCo')
        self.job = JobPosting.objects.create(
            title='Product Designer', company=self.company, category=self.category,
            description='Design things.', location='Remote', salary_min=80000, salary_max=110000,
        )
        self.user = User.objects.create_user(username='apitester', password='testpass123')

    def test_job_list_api(self):
        response = self.client.get('/api/jobs/')
        self.assertEqual(response.status_code, 200)
        self.assertIn('results', response.json())

    def test_job_detail_api(self):
        response = self.client.get(f'/api/jobs/{self.job.slug}/')
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json()['title'], 'Product Designer')

    def test_job_search_api(self):
        response = self.client.get('/api/jobs/', {'q': 'Product Designer'})
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json()['count'], 1)

    def test_saved_jobs_api_requires_auth(self):
        response = self.client.get('/api/saved-jobs/')
        self.assertIn(response.status_code, (401, 403))

    def test_saved_jobs_api_authenticated(self):
        self.client.login(username='apitester', password='testpass123')
        response = self.client.post('/api/saved-jobs/', {'job_id': self.job.id})
        self.assertEqual(response.status_code, 201)
        self.assertTrue(SavedJob.objects.filter(user=self.user, job=self.job).exists())


class EmployerJobPostingFlowTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.category = JobCategory.objects.create(name='Software Engineering')
        self.skill = Skill.objects.create(name='Python')

        self.employer = User.objects.create_user(username='employer1', password='testpass123')
        self.employer.profile.role = 'employer'
        self.employer.profile.save()

        self.seeker = User.objects.create_user(username='seeker1', password='testpass123')

    def test_seeker_cannot_access_employer_job_create(self):
        self.client.login(username='seeker1', password='testpass123')
        response = self.client.get(reverse('jobs:job_create'))
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse('accounts:dashboard'))

    def test_anonymous_redirected_from_employer_pages(self):
        response = self.client.get(reverse('jobs:my_job_postings'))
        self.assertEqual(response.status_code, 302)

    def test_employer_without_company_is_redirected_to_setup(self):
        self.client.login(username='employer1', password='testpass123')
        response = self.client.get(reverse('jobs:my_job_postings'))
        self.assertRedirects(response, reverse('jobs:company_setup'))

    def test_employer_can_create_company(self):
        self.client.login(username='employer1', password='testpass123')
        response = self.client.post(reverse('jobs:company_setup'), {
            'name': 'Employer One Co', 'industry': 'Tech', 'size': 'small',
            'headquarters': 'Remote', 'website': '', 'description': 'We build things.',
            'founded_year': '2020',
        })
        self.assertRedirects(response, reverse('jobs:my_job_postings'))
        self.assertTrue(Company.objects.filter(name='Employer One Co', owner=self.employer).exists())

    def test_employer_can_post_and_edit_a_job(self):
        self.client.login(username='employer1', password='testpass123')
        Company.objects.create(name='Employer One Co', owner=self.employer)

        response = self.client.post(reverse('jobs:job_create'), {
            'title': 'Backend Engineer', 'category': self.category.id,
            'description': 'Build the backend.', 'responsibilities': '', 'requirements': '',
            'location': 'Remote', 'remote_option': 'remote', 'experience_level': 'mid',
            'employment_type': 'full_time', 'salary_min': '90000', 'salary_max': '120000',
            'currency': 'USD', 'skills': [self.skill.id],
        })
        self.assertRedirects(response, reverse('jobs:my_job_postings'))
        job = JobPosting.objects.get(title='Backend Engineer')
        self.assertEqual(job.company.owner, self.employer)
        self.assertIn(self.skill, job.skills.all())

        response = self.client.post(reverse('jobs:job_edit', args=[job.slug]), {
            'title': 'Senior Backend Engineer', 'category': self.category.id,
            'description': 'Build the backend.', 'responsibilities': '', 'requirements': '',
            'location': 'Remote', 'remote_option': 'remote', 'experience_level': 'senior',
            'employment_type': 'full_time', 'salary_min': '110000', 'salary_max': '140000',
            'currency': 'USD', 'is_active': 'on',
        })
        self.assertRedirects(response, reverse('jobs:my_job_postings'))
        job.refresh_from_db()
        self.assertEqual(job.title, 'Senior Backend Engineer')
        self.assertEqual(job.skills.count(), 0)  # not resubmitted, so cleared

    def test_employer_cannot_edit_other_companys_job(self):
        other_owner = User.objects.create_user(username='employer2', password='testpass123')
        other_owner.profile.role = 'employer'
        other_owner.profile.save()
        other_company = Company.objects.create(name='Other Co', owner=other_owner)
        job = JobPosting.objects.create(
            title='Other Job', company=other_company, category=self.category,
            description='...', location='Remote',
        )

        self.client.login(username='employer1', password='testpass123')
        Company.objects.create(name='Employer One Co', owner=self.employer)
        response = self.client.get(reverse('jobs:job_edit', args=[job.slug]))
        self.assertRedirects(response, reverse('jobs:my_job_postings'))

    def test_toggle_active_requires_ownership(self):
        other_owner = User.objects.create_user(username='employer3', password='testpass123')
        other_company = Company.objects.create(name='Third Co', owner=other_owner)
        job = JobPosting.objects.create(
            title='Third Job', company=other_company, category=self.category,
            description='...', location='Remote', is_active=True,
        )
        self.client.login(username='employer1', password='testpass123')
        # employer1 needs their own company so the post-redirect landing page
        # (my_job_postings) itself resolves to 200 rather than bouncing again
        # to company_setup — the ownership check under test is independent of this.
        Company.objects.create(name='Employer One Co', owner=self.employer)
        response = self.client.post(reverse('jobs:job_toggle_active', args=[job.slug]))
        self.assertRedirects(response, reverse('jobs:my_job_postings'))
        job.refresh_from_db()
        self.assertTrue(job.is_active)  # unchanged


class ApplicationFormFlowTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.category = JobCategory.objects.create(name='Software Engineering')
        self.employer = User.objects.create_user(
            username='appflow_employer', password='testpass123', email='employer@example.com'
        )
        self.employer.profile.role = 'employer'
        self.employer.profile.save()
        self.company = Company.objects.create(name='AppFlow Co', owner=self.employer)
        self.job = JobPosting.objects.create(
            title='QA Engineer', company=self.company, category=self.category,
            description='...', location='Remote',
        )
        self.seeker = User.objects.create_user(
            username='appflow_seeker', password='testpass123', email='seeker@example.com'
        )

    def test_apply_form_renders_on_get(self):
        self.client.login(username='appflow_seeker', password='testpass123')
        response = self.client.get(reverse('jobs:apply_to_job', args=[self.job.slug]))
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, 'jobs/apply_form.html')

    def test_apply_with_cover_letter_and_resume(self):
        self.client.login(username='appflow_seeker', password='testpass123')
        resume = SimpleUploadedFile('resume.pdf', b'%PDF-1.4 fake content', content_type='application/pdf')
        response = self.client.post(reverse('jobs:apply_to_job', args=[self.job.slug]), {
            'cover_letter': 'I would love to join your QA team.',
            'resume': resume,
        })
        self.assertEqual(response.status_code, 302)
        application = Application.objects.get(user__username='appflow_seeker', job=self.job)
        self.assertEqual(application.cover_letter, 'I would love to join your QA team.')
        self.assertTrue(application.resume.name.startswith('resumes/'))

    def test_apply_without_resume_still_works(self):
        self.client.login(username='appflow_seeker', password='testpass123')
        response = self.client.post(reverse('jobs:apply_to_job', args=[self.job.slug]), {'cover_letter': ''})
        self.assertEqual(response.status_code, 302)
        self.assertTrue(Application.objects.filter(user__username='appflow_seeker', job=self.job).exists())

    def test_cannot_reapply_redirects_to_job_detail(self):
        self.client.login(username='appflow_seeker', password='testpass123')
        self.client.post(reverse('jobs:apply_to_job', args=[self.job.slug]), {'cover_letter': ''})
        response = self.client.get(reverse('jobs:apply_to_job', args=[self.job.slug]))
        self.assertRedirects(response, self.job.get_absolute_url())

    def test_employer_notified_by_email_on_new_application(self):
        self.client.login(username='appflow_seeker', password='testpass123')
        mail.outbox = []
        self.client.post(reverse('jobs:apply_to_job', args=[self.job.slug]), {'cover_letter': ''})
        self.assertEqual(len(mail.outbox), 1)
        self.assertIn(self.employer.email, mail.outbox[0].to)
        self.assertIn('QA Engineer', mail.outbox[0].subject)


class ApplicantTrackingTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.category = JobCategory.objects.create(name='Software Engineering')
        self.employer = User.objects.create_user(username='track_employer', password='testpass123')
        self.employer.profile.role = 'employer'
        self.employer.profile.save()
        self.company = Company.objects.create(name='TrackCo', owner=self.employer)
        self.job = JobPosting.objects.create(
            title='Support Engineer', company=self.company, category=self.category,
            description='...', location='Remote',
        )
        self.applicant = User.objects.create_user(
            username='track_applicant', password='testpass123', email='applicant@example.com'
        )
        self.application = Application.objects.create(user=self.applicant, job=self.job)

    def test_other_employer_cannot_view_applicants(self):
        other = User.objects.create_user(username='track_other', password='testpass123')
        other.profile.role = 'employer'
        other.profile.save()
        # other needs their own company, otherwise the post-redirect landing page
        # (my_job_postings) itself redirects again to company_setup — the ownership
        # check under test here is independent of that.
        Company.objects.create(name='Other Co', owner=other)
        self.client.login(username='track_other', password='testpass123')
        response = self.client.get(reverse('jobs:job_applicants', args=[self.job.slug]))
        self.assertRedirects(response, reverse('jobs:my_job_postings'))

    def test_seeker_cannot_view_applicants(self):
        self.client.login(username='track_applicant', password='testpass123')
        response = self.client.get(reverse('jobs:job_applicants', args=[self.job.slug]))
        self.assertEqual(response.status_code, 302)

    def test_owner_sees_applicant_list(self):
        self.client.login(username='track_employer', password='testpass123')
        response = self.client.get(reverse('jobs:job_applicants', args=[self.job.slug]))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'track_applicant')

    def test_owner_can_update_status_and_applicant_is_notified(self):
        self.client.login(username='track_employer', password='testpass123')
        mail.outbox = []
        response = self.client.post(reverse('jobs:job_applicants', args=[self.job.slug]), {
            'application_id': self.application.id, 'status': 'interview',
        })
        self.assertRedirects(response, reverse('jobs:job_applicants', args=[self.job.slug]))
        self.application.refresh_from_db()
        self.assertEqual(self.application.status, 'interview')
        self.assertEqual(len(mail.outbox), 1)
        self.assertIn('applicant@example.com', mail.outbox[0].to)

    def test_no_email_sent_when_status_unchanged(self):
        self.client.login(username='track_employer', password='testpass123')
        mail.outbox = []
        self.client.post(reverse('jobs:job_applicants', args=[self.job.slug]), {
            'application_id': self.application.id, 'status': 'applied',
        })
        self.assertEqual(len(mail.outbox), 0)
